### ISSUE TITLE
使用第三方存储时多个管理节点共享ansible状态数据问题

### ISSUE THREAD

**Issue by barnettZQG** [goodrain/rainbond-ansible#109]
目前的实现是基于第一个管理节点的nfs-server共享的状态数据：
```
- name: Rainbond | Add share
  template:
    src: share.sh.j2
    dest: /tmp/share.sh
    mode: 0777
  when: check_manage_share.stat.isreg is not defined and storage_type == "nfs"

- name: Rainbond | Run share
  shell: bash /tmp/share.sh
  when: check_manage_share.stat.isreg is not defined and storage_type == "nfs"
```
我们需要实现在使用任何存储的情况下管理节点能够共享ansible脚本和状态数据，以支持集群API触发安装任务。
或在node服务中实现任务塞选，安装任务只在第一个管理节点执行。
